#pragma once

#define CAM_OK 0
#define CAM_TVP_FAILED_TO_INIT 1
#define CAM_TVP_FAILED_TO_SS 2
#define CAM_TVP_FAILED_TO_COMMUNICATE 3
#define CAM_TVP_FAILED_TO_SET_OUTPUT 4
#define CAM_TVP_FAILED_TO_SET_CLOCK 5
#define CAM_TVP_FAILED_TO_SET_AVID 6
#define CAM_TVP_FAILED_TO_SET_FORMAT 7

#define CAM_CAMERA_FAILED_TO_INIT 10
#define CAM_B2B_FAILED_TO_INIT 11